version: '3'
services:
  fwdev:
    container_name: fitswarm-dev
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - .:/fitswarm
      - ./docker/dev/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
    ports:
      - "0.0.0.0:20000:9000"
      - "0.0.0.0:20001:8000"
    depends_on:
      - mysql
    links:
      - mysql
    command: php artisan serve --host=0.0.0.0 --port=8000
  mysql:
    container_name: fitswarm-mysql
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fitswarm
      MYSQL_DATABASE: fitswarm
      MYSQL_USER: fitswarm
      MYSQL_PASSWORD: fitswarm
    ports:
      - "3306"
      - "33306:3306"
volumes:
  db_data:
