@extends('admin.layouts.base')
@section('body')
<form id="file-upload" class="upload" method="post" action="{{ isset($entry->id) ? action('Admin\InstructorController@edit', $entry->id) : action('Admin\InstructorController@create') }}" enctype="multipart/form-data">
<div class="inner clearfix">

<p class="dox-detail-top">This page enables the administrator to change every detail that appears on an instructor’s profile page.</p>

{!! HTMLFormHelper::legend('Personal Details') !!}

<p class="dox-detail-heading">To make an amend simply type the revised entry into the relevant box.</p>

{!! HTMLFormHelper::text('First Name *', 'name', $entry->name, $errors) !!}
{!! HTMLFormHelper::text('Last Name *', 'surname', $entry->surname, $errors) !!}
{!! HTMLFormHelper::text('Email *', 'email', $entry->email, $errors) !!}
{!! HTMLFormHelper::password('Password', 'password', $errors, [], 'Leave blank to retain current password.') !!}
{!! HTMLFormHelper::file('Profile Image', 'img', $entry->img, $errors, [], 'To change an instructor’s Profile Image simply click on the ‘Profile image’ box and Browse for a suitable replacement. The same action can be taken to change the Signature Image. Selected images can be in any recognised picture format (JPEG, PNG, GIF, EPS). The subject matter should be placed centrally to allow for slight cropping around the edges.', ['type' => 'image', 'preview' => AssetHelper::file('instructors', $entry->id, $entry->img, '200x0')]) !!}
{!! HTMLFormHelper::select('Mobile Country *', 'mobile_country_id', $countries_codes_array, $entry->mobile_country_id, $errors, ['class' => 'chosen-select']) !!}
{!! HTMLFormHelper::text('Mobile Number', 'mobile', $entry->mobile, $errors) !!}
{!! HTMLFormHelper::text('DOB', 'dob', strlen($entry->dob) > 0 ? DateHelper::showDate($entry->dob) : '', $errors, ['data-date-format' => 'YYYY-MM-DD'], 'Date of Birth - In European format YYYY-MM-DD.', ['type' => 'date', 'data' => '']) !!}
{!! HTMLFormHelper::select('Country *', 'country_id', $countries_array, $entry->country_id, $errors, ['class' => 'chosen-select']) !!}
{!! HTMLFormHelper::select('Timezone *', 'timezone', $timezones_array, $entry->timezone, $errors, ['class' => 'chosen-select']) !!}

<br>

{!! HTMLFormHelper::legend('Additional Profile Details') !!}
{!! HTMLFormHelper::textarea('Bio', 'bio', $entry->bio, $errors) !!}
{!! HTMLFormHelper::textarea('Accreditations', 'accreditations', $entry->accreditations, $errors) !!}
{!! HTMLFormHelper::select('Years Experience *', 'years_experience', $experience_array, $entry->years_experience, $errors, ['class' => 'chosen-select']) !!}
{!! HTMLFormHelper::file('Signature Image', 'signature_img', $entry->signature_img, $errors, [], '', ['type' => 'image', 'preview' => AssetHelper::file('instructors', $entry->id, $entry->signature_img, '200x0')]) !!}

<br>

{!! HTMLFormHelper::legend('Social Networks') !!}

<p class="dox-detail-heading">Cut and paste relevant URLs into the boxes as appropriate. If you require all instructors to display corporate URLs, on receipt of information, Fitswarm will ensure data is automatically uploaded to all instructor profiles.</p>

{!! HTMLFormHelper::text('Facebook URL', 'social_facebook', $entry->social_facebook, $errors) !!}
{!! HTMLFormHelper::text('Twitter URL', 'social_twitter', $entry->social_twitter, $errors) !!}
{!! HTMLFormHelper::text('Instagram URL', 'social_instagram', $entry->social_instagram, $errors) !!}
{!! HTMLFormHelper::text('YouTube URL', 'social_youtube', $entry->social_youtube, $errors) !!}
{!! HTMLFormHelper::text('LinkedIn URL', 'social_linkedin', $entry->social_linkedin, $errors) !!}
{!! HTMLFormHelper::text('Google+ URL', 'social_googleplus', $entry->social_googleplus, $errors) !!}
{!! HTMLFormHelper::text('Snapchat Username', 'social_snapchat', $entry->social_snapchat, $errors) !!}
{!! HTMLFormHelper::text('Website URL', 'social_www', $entry->social_www, $errors) !!}

<br>

{!! HTMLFormHelper::legend('Financial Details') !!}

<p class="dox-detail-heading">Data input here depicts where income generated by the instructor will be sent.</p>

{!! HTMLFormHelper::text('Bank Name', 'bank_name', $entry->bank_name, $errors) !!}
{!! HTMLFormHelper::text('Account Holder Name', 'bank_account_holder', $entry->bank_account_holder, $errors) !!}
{!! HTMLFormHelper::text('Account Number', 'bank_account_number', $entry->bank_account_number, $errors) !!}
{!! HTMLFormHelper::text('Sort Code', 'bank_sort_code', $entry->bank_sort_code, $errors) !!}
{!! HTMLFormHelper::text('PayPal Email', 'paypal_email', $entry->paypal_email, $errors) !!}

<br>

{!! HTMLFormHelper::legend('Legal Details') !!}

<p class="dox-detail-heading">Both ‘Has Insurance’ and ‘Has Accreditation’ need to read ‘Yes’ for an instructor to be able to activate their profile.</p>

{!! HTMLFormHelper::radiogroup('Has Insurance?', 'has_insurance', [-1 => 'Not Specified', 1 => 'Yes', 0 => 'No'], $entry->has_insurance, $errors) !!}
{!! HTMLFormHelper::radiogroup('Has Accreditations?', 'has_accreditations', [-1 => 'Not Specified', 1 => 'Yes', 0 => 'No'], $entry->has_accreditations, $errors) !!}

<br>

{!! HTMLFormHelper::legend('Administrative') !!}

@if (isset($entry->id))
    {!! HTMLFormHelper::string('IP Address', $entry->ip, '', '', 'This is bespoke to the instructor and used within the Moderation page to block an instructor.') !!}
@endif

{!! HTMLFormHelper::radiogroup('Status', 'status', [1 => 'Active', 0 => 'Inactive'], $entry->status, $errors, [], 'An Instructor who has completed the registration form and successfully verified their activation on the automated email received post registration, will be automatically listed as ‘Active’. If an Instructor is shown to be ‘Inactive’ it is likely to be because they have not responded to an automated email, sent to the address specified in their Registration Form, requesting that they verify their activation. By ticking ‘Active’ the administrator will effectively verify activation on behalf of the Instructor.') !!}
{!! HTMLFormHelper::submit(isset($entry->id) ? 'Save Changes' : 'Create New', ['class' => 'right']) !!}
</div>
{!! csrf_field() !!}
</form>
@stop
