<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
<script src="{{ AssetHelper::asset('static/admin/js/libs/bootstrap.min.js') }}"></script>
<script src="{{ AssetHelper::asset('static/admin/js/libs/waypoints.js') }}"></script>
<script src="{{ AssetHelper::asset('static/admin/js/libs/jquery.counterup.min.js') }}"></script>
<script src="{{ AssetHelper::asset('static/admin/js/libs/chosen.jquery.min.js') }}"></script>
<script src="{{ AssetHelper::asset('static/admin/js/libs/input.slider.js') }}"></script>
<script src="{{ AssetHelper::asset('static/admin/js/libs/bxslider.js') }}"></script>
<script src="{{ AssetHelper::asset('static/admin/js/libs/prettyCheckable.min.js') }}"></script>
<script src="{{ AssetHelper::asset('static/admin/js/libs/jquery.dataTables.min.js') }}"></script>
<script src="{{ AssetHelper::asset('static/admin/js/libs/dataTables.conditionalPaging.js') }}"></script>
<script src="{{ AssetHelper::asset('static/admin/js/libs/chartist/chartist.min.js') }}"></script>
<script src="{{ AssetHelper::asset('static/admin/js/libs/chartist/chartist-plugin-tooltip.js') }}"></script>
<script src="{{ AssetHelper::asset('static/admin/js/libs/datepicker/moment.min.js') }}"></script>
<script src="{{ AssetHelper::asset('static/admin/js/libs/datepicker/bootstrap-datetimepicker.min.js') }}"></script>
<script src="{{ AssetHelper::asset('static/admin/js/libs/jquery.matchHeight-min.js') }}"></script>
<script src="{{ AssetHelper::asset('static/admin/js/libs/jquery.fileupload.js') }}"></script>
<script src="{{ AssetHelper::asset('static/admin/js/libs/fileStyle.js') }}"></script>
<script src="{{ AssetHelper::asset('static/admin/js/libs/tagsInput.js') }}"></script>
<script src="{{ AssetHelper::asset('static/admin/js/libs/jquery.ba-throttle-debounce.min.js') }}"></script>
<script src="{{ AssetHelper::asset('static/admin/js/plugins.js') }}"></script>
<script src="{{ AssetHelper::asset('static/admin/js/upload.js') }}"></script>
<script src="{{ AssetHelper::asset('static/admin/js/app.js') }}"></script>
<script src="{{ AssetHelper::asset('static/admin/js/utils.js') }}"></script>
